### ISSUE TITLE
cannot find symbol

### ISSUE THREAD

**Issue by corentin-gautier** [gitawego/cordova-webview-setting#2]
Hey,

So I've been having this error for a while : 

``` shell
viewsetting\WebviewSetting.java:31: error: cannot find symbol
                    webView.getSettings().setLoadWithOverviewMode(true);
                           ^
  symbol:   method getSettings()
  location: variable webView of type CordovaWebView
```

For what i've seen by looking it up, it looks like getSettings is no longer available on webView ? Do you know anything about that ? Sorry if it's a noob question :)

**Comment by CramericaIndustries** [comment]
Same issue here. Did you find a solution @corentin-gautier ?

**Comment by mrKaizen** [comment]
Opened and updated cordova in my old project, sadly I have now the same error and no solution. Any idea? Tks in advance.

**Comment by brittonk** [comment]
if anyone else comes upon this, this fork fixed it for me:

https://github.com/RomaRogov/cordova-webview-setting
